In [ ]:
import numpy as np
import pprint

In [14]:
NPY_PATH = r"D:\dev\karst-terrain-classification\data\processed\minimal_exploration\testbed_features_ph_directional.npy"

data = np.load(NPY_PATH)

# Direction 0 degrees
pprint.pp(data[0][:50]) # connected components
pprint.pp(data[0][50:100]) # loops/holes

# 45 degrees
pprint.pp(data[0][100:150])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.])
array([ 1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  5.,  5.,  5.,  6.,  6.,  7.,  7.,
        7.,  7.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,  0.])
array([2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.])
